### PR TITLE
Use rollup to create flat bundles

### PR DESCRIPTION
**Pull request by Andarist**
**warning**
this is somewhat a breaking change if somebody imported anything using a "deep path", i.e.
```js
require('react-automata/lib/Action')
```

Personally I don't consider package's directory structure part of its public API 🤷‍♂️

### CODE REVIEW

**Comment by takahiro-saeki** [comment]
it would be great choice!

**Comment by MicheleBertoli** [comment]
Thank you very much @Andarist, this is pretty awesome.
`babel-cli` and `cross-env` can be removed, right?

**Comment by Andarist** [comment]
@MicheleBertoli good eye, fixed 😉

**Comment by MicheleBertoli** [comment]
Thank you very much, @Andarist 🙌

**Pull request merged**
