### PR TITLE
Add render prop to Conditional

### PR DESCRIPTION
**Pull request by ferdinandsalis**
Here is my first stab at adding tests and some documentation. I am sure you are still making a few changes for the release, so feel free to discard the pull request or make changes.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
This is awesome, thank you very much @ferdinandsalis.

I've got just a few questions/considerations but it looks great to me:
- why are we passing `{ visibile }` instead of just `visibile`? (this is the only thing that prevented me from pressing "merge" straight away : )).
- I suggest we use [render props](https://reactjs.org/docs/render-props.html) rather than "function as child".
- it's might worth reorganizing the tests and separate the callbacks from the visible (children / render props) and not visible states - I/we can do it later.

**Comment by ferdinandsalis** [comment]
* Do we ever need to pass in any other data, if not I guess we could just pass the boolean
* Will do. Should we maybe allow both?
* Yes I thought so too. However I am not that apt yet when it comes to testing. Will try, maybe …

Thanks for the feedback!

**Comment by MicheleBertoli** [comment]
- I would go for the boolean approach, and if we ever need more data we can pass multiple params (unless they become too many :))
- Although I tend to prefer the "function as child" approach, I would go with the `render` prop (as it seems more common, and it's used in the official React docs)
- Let's consider this a nice to have - I'll be happy to merge and refactor the tests later

Thank you very much one more time.

**Comment by MicheleBertoli** [comment]
🙌

**Pull request merged**
